---
roles:
  - name: nginxinc.nginx
    version: 0.24.1
  - name: nginxinc.nginx_config
    version: 0.3.3
  - name: cloudalchemy.grafana
    version: 0.18.0
  - name: dj-wasabi.telegraf
    version: 0.14.0

collections:
  - name: community.general
    version: 8.2.0
  - name: community.grafana
    version: 1.9.1
  - name: ansible.windows
    version: 2.1.0
  - name: amazon.aws
    version: 7.2.0
  - name: prometheus.prometheus
    version: 0.11.2
