---
roles:
  - name: cloudalchemy.prometheus
    version: 2.16.2
  - name: nginxinc.nginx
    version: 0.23.0
  - name: nginxinc.nginx_config
    version: 0.3.3
  - name: cloudalchemy.grafana
    version: 0.18.0
  - name: cloudalchemy.node_exporter
    version: 0.22.0
  - name: cloudalchemy.blackbox-exporter
    version: 0.9.3
  - name: dj-wasabi.telegraf
    version: 0.14.0

collections:
  - name: community.general
    version: 4.4.0
  - name: community.grafana
    version: 1.5.3
  - name: ansible.windows
    version: 2.1.0
  - name: amazon.aws
    version: 3.1.1
