- name: cloudalchemy.prometheus
  version: 2.15.5
- name: nginxinc.nginx
  version: 0.14.0
- name: cloudalchemy.grafana
  version: 0.18.0
- name: cloudalchemy.node-exporter
  version: 0.21.5
- name: cloudalchemy.blackbox-exporter
  version: 0.9.2
- name: dj-wasabi.telegraf
  version: 0.12.0
