- name: cloudalchemy.prometheus
  version: 2.16.1
- name: nginxinc.nginx
  version: 0.14.0
- name: cloudalchemy.grafana
  version: 0.18.0
- name: cloudalchemy.node_exporter
  version: 0.22.0
- name: cloudalchemy.blackbox-exporter
  version: 0.9.3
- name: dj-wasabi.telegraf
  version: 0.13.0
