- name: cloudalchemy.prometheus
  version: 2.15.5
- name: nginxinc.nginx
  version: 0.12.0
- name: cloudalchemy.grafana
  version: 0.17.0
- name: cloudalchemy.node-exporter
  version: 0.16.0
- name: cloudalchemy.blackbox-exporter
  version: 0.9.1
- name: dj-wasabi.telegraf
  version: 0.12.0
