---
roles:
  - name: nginxinc.nginx
    version: 0.24.3
  - name: nginxinc.nginx_config
    version: 0.3.3
  - name: dj-wasabi.telegraf
    version: 0.14.1

collections:
  - name: community.general
    version: 9.5.1
  - name: community.grafana
    version: 2.1.0
  - name: ansible.windows
    version: 2.1.0
  - name: amazon.aws
    version: 7.2.0
  - name: prometheus.prometheus
    version: 0.19.0
