apiVersion: 1

datasources:
  - name: Prometheus-default
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
