{
 "title": "prom-client default metrics",
 "tags": [
  "Node.js",
  "prom-client",
  "created-by-shields.io"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(nodejs_version_info, env)"
   },
   {
    "name": "instance",
    "query": "label_values(nodejs_version_info{env=~\"$env\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lag of event loop in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js versions",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(nodejs_version_info{instance=~\"$instance\", env=~\"$env\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process heap space size used from node.js in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{space}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Process heap space size available from node.js in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{space}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Process heap space size total from node.js in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{space}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Process memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "Resident memory size in bytes ({{instance}})"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "Virtual memory size in bytes ({{instance}})"
    },
    {
     "expr": "process_heap_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "Process heap size in bytes ({{instance}})"
    }
   ]
  },
  {
   "title": "Nodejs external memory size in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of active requests/handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "active requests ({{instance}})"
    },
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\", env=~\"$env\"}",
     "legendFormat": "active handles ({{instance}})"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "delta(process_cpu_user_seconds_total{instance=~\"$instance\", env=~\"$env\"}[1m])",
     "legendFormat": "user CPU ({{instance}})"
    },
    {
     "expr": "delta(process_cpu_system_seconds_total{instance=~\"$instance\", env=~\"$env\"}[1m])",
     "legendFormat": "system CPU ({{instance}})"
    }
   ]
  }
 ]
}