{
 "title": "services",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  { "title": "Badge usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All the individual services",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(service_requests_total{env=~\"$env\"}[$__range])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "All the individual services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(service_requests_total{env=~\"$env\"}[$__range])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "All the services families",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(service_requests_total{env=~\"$env\"}[$__range])) by (family)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "All the services families",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(service_requests_total{env=~\"$env\"}[$__range])) by (family)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Requests by category",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by(category)(increase(service_requests_total{env=~\"$env\"}[$__range]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "All redirectors for the individual services",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(service_requests_total{env=~\"$env\", exported_service=~\".+_redirect\"}[$__range])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Total requests per day per server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(increase(service_requests_total{env=~\"$env\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(service_requests_total{env=~\"$env\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Service response time (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(service_response_millis_sum{env=~\"$env\"}[1m])/rate(service_response_millis_count{env=~\"$env\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Response sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Service response size in bytes",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(service_response_bytes_bucket{family=\"dynamic\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service response size in bytes (all dynamic badges)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(service_response_bytes_bucket{exported_service=\"dynamic_json\"}[$__range])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service response size in bytes (dynamic JSON)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(service_response_bytes_bucket{exported_service=\"dynamic_json\"}[$__range])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service response size in bytes (dynamic XML)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(service_response_bytes_bucket{exported_service=\"dynamic_xml\"}[$__range])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service response size in bytes (dynamic YAML)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(service_response_bytes_bucket{exported_service=\"dynamic_yaml\"}[$__range])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Rate limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Rate limit exceeded request per-second rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rate_limit_exceeded_total[1m])",
     "legendFormat": "{{rate_limit_type}} - {{instance}}"
    }
   ]
  }
 ]
}